---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: acme
spec:
  interval: 120m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: acme
spec:
  interval: 15m
  chart:
    spec:
      chart: cert-manager
      version: ">=1.7.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: acme
      interval: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true

