---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./cluster
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  timeout: 1m
  validation: client
