apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - podmonitor.yaml
configMapGenerator:
  - name: flux-grafana-dashboards
    namespace: monitoring
    files:
      - control-plane.json
      - cluster.json
    options:
      labels:
        grafana_dashboard: "1"
