---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-config
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  timeout: 2m
  validation: client
  healthChecks:
    - kind: Deployment
      name: prometheus-operator-kube-p-operator
      namespace: monitoring
    - kind: Deployment
      name: prometheus-operator-grafana
      namespace: monitoring
