---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-chart
  namespace: ingress
spec:
  interval: 120m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: ">=4.0.18"
      sourceRef:
        kind: HelmRepository
        name: ingress-chart
        namespace: ingress
      interval: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    controller:
      hostPort:
        enabled: true
      service:
        enabled: true
        type: NodePort
        targetPorts:
          http: http
        annotations:
          kubernetes.io/ingress.global-static-ip-name: "ingress-address"
      nodeSelector:
        kubernetes.io/os: linux
        ingress-ready: "true"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Equal
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
