replicaCount: 1

image:
  repository: quay.io/heubeck/examiner
  pullPolicy: IfNotPresent
  tag: "1.3.0"

service:
  type: ClusterIP
  port: 80

container:
  port: 8080

configuration: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

canary:
  enabled: false
