---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-config
  interval: 10s
  path: ./apps
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  timeout: 2m
  validation: client
