---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-config
  interval: 5m0s
  path: ./infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  timeout: 15m
  validation: client
  healthChecks:
    # acme
    - kind: Deployment
      name: cert-manager
      namespace: acme
    # monitoring
    - kind: Deployment
      name: prometheus-operator-kube-p-operator
      namespace: monitoring
    - kind: Deployment
      name: prometheus-operator-grafana
      namespace: monitoring
    # linkerd
    - kind: Deployment
      name: linkerd-destination
      namespace: linkerd
    - kind: Deployment
      name: linkerd-identity
      namespace: linkerd
    - kind: Deployment
      name: linkerd-proxy-injector
      namespace: linkerd
