---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-config
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 1m0s
  path: ./infrastructure-config
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  timeout: 5m
  validation: client
  healthChecks:
    # ingress
    - kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress
    # linkerd
    - kind: Deployment
      name: smi-adaptor
      namespace: linkerd-smi
    - kind: Deployment
      name: metrics-api
      namespace: linkerd-viz
    - kind: Deployment
      name: prometheus
      namespace: linkerd-viz
    - kind: Deployment
      name: tap
      namespace: linkerd-viz
    - kind: Deployment
      name: tap-injector
      namespace: linkerd-viz
    - kind: Deployment
      name: web
      namespace: linkerd-viz
