---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-config
  interval: 5m0s
  path: ./infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  timeout: 5m
  validation: client
  healthChecks:
    # acme
    - kind: HelmRelease
      name: cert-manager
      namespace: acme
    - kind: Deployment
      name: cert-manager
      namespace: acme
    # monitoring
    - kind: HelmRelease
      name: prometheus-operator
      namespace: monitoring
    - kind: Deployment
      name: prometheus-operator-kube-p-operator
      namespace: monitoring
    - kind: Deployment
      name: prometheus-operator-grafana
      namespace: monitoring
    # ingress
    - kind: HelmRelease
      name: ingress-nginx
      namespace: ingress
    - kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress
