---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-config
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 1m0s
  path: ./infrastructure-config
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  timeout: 1m
  validation: client
