apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "echo.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "echo.labels" . | nindent 4 }}
data:
    {{- toYaml .Values.configuration | nindent 4 }}
